import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'package:provider/provider.dart';

import '../viewmodels/wallet_viewmodel.dart';
import '../../authentication/models/user_model.dart';
import '../../authentication/widgets/auth_button.dart';
import '../models/withdrawal_request_model.dart';

class RequestWithdrawalScreen extends StatefulWidget {
  final double availableBalance;

  const RequestWithdrawalScreen({super.key, required this.availableBalance});

  @override
  State<RequestWithdrawalScreen> createState() => _RequestWithdrawalScreenState();
}

class _RequestWithdrawalScreenState extends State<RequestWithdrawalScreen> {
  final _formKey = GlobalKey<FormState>();
  final _amountController = TextEditingController();
  final _bankNameController = TextEditingController();
  final _accountNameController = TextEditingController();
  final _accountNumberController = TextEditingController();
  
  bool _isLoading = false;

  @override
  void dispose() {
    _amountController.dispose();
    _bankNameController.dispose();
    _accountNameController.dispose();
    _accountNumberController.dispose();
    super.dispose();
  }

  Future<void> _submitRequest() async {
    if (!_formKey.currentState!.validate()) return;

    final user = UserModel.currentUser;
    if (user == null) return;

    setState(() => _isLoading = true);

    try {
      final amount = double.parse(_amountController.text);
      
      final request = WithdrawalRequestModel(
        id: '', // Generated by WalletRepository
        sellerId: user.id,
        sellerName: user.name,
        amount: amount,
        bankDetails: {
          'bankName': _bankNameController.text.trim(),
          'accountName': _accountNameController.text.trim(),
          'accountNumber': _accountNumberController.text.trim(),
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await context.read<WalletViewModel>().requestWithdrawal(request);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Withdrawal request submitted successfully.'),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to submit request: $e'),
            backgroundColor: Theme.of(context).colorScheme.error,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Request Withdrawal',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18.sp),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: EdgeInsets.all(20.w),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  padding: EdgeInsets.all(16.w),
                  decoration: BoxDecoration(
                    color: Colors.blue.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(12.r),
                    border: Border.all(color: Colors.blue.withOpacity(0.3)),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.info_outline, color: Colors.blue, size: 24.w),
                      SizedBox(width: 12.w),
                      Expanded(
                        child: Text(
                          'Available Balance: ${widget.availableBalance.toStringAsFixed(2)} EGP\nWithdrawal requests may take 2-3 business days to process.',
                          style: TextStyle(fontSize: 13.sp, color: Colors.blue[800]),
                        ),
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 24.h),
                
                Text('Withdrawal Amount', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15.sp)),
                SizedBox(height: 8.h),
                TextFormField(
                  controller: _amountController,
                  keyboardType: const TextInputType.numberWithOptions(decimal: true),
                  decoration: InputDecoration(
                    hintText: 'e.g. 500',
                    suffixText: 'EGP',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                  ),
                  validator: (value) {
                    if (value == null || value.isEmpty) return 'Please enter an amount';
                    final amount = double.tryParse(value);
                    if (amount == null) return 'Please enter a valid number';
                    if (amount <= 0) return 'Amount must be greater than 0';
                    if (amount > widget.availableBalance) return 'Exceeds available balance';
                    return null;
                  },
                ),
                
                SizedBox(height: 20.h),
                Text('Bank Name', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15.sp)),
                SizedBox(height: 8.h),
                TextFormField(
                  controller: _bankNameController,
                  decoration: InputDecoration(
                    hintText: 'e.g. CIB, NBE',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                  ),
                  validator: (value) => value == null || value.isEmpty ? 'Required field' : null,
                ),

                SizedBox(height: 20.h),
                Text('Account Holder Name', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15.sp)),
                SizedBox(height: 8.h),
                TextFormField(
                  controller: _accountNameController,
                  decoration: InputDecoration(
                    hintText: 'e.g. John Doe',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                  ),
                  validator: (value) => value == null || value.isEmpty ? 'Required field' : null,
                ),

                SizedBox(height: 20.h),
                Text('Account Number / IBAN', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15.sp)),
                SizedBox(height: 8.h),
                TextFormField(
                  controller: _accountNumberController,
                  decoration: InputDecoration(
                    hintText: 'Enter your account number',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                  ),
                  validator: (value) => value == null || value.isEmpty ? 'Required field' : null,
                ),

                SizedBox(height: 40.h),
                SizedBox(
                  width: double.infinity,
                  child: AuthButton(
                    text: 'Submit Request',
                    onPressed: _isLoading ? null : _submitRequest,
                    isLoading: _isLoading,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
