// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDek6zMI2YTmqaZadXlF2wXt553o_q7q7s',
    appId: '1:460987873980:android:c54c4ac9ffafc75783aeb9',
    messagingSenderId: '460987873980',
    projectId: 'barter-30a05',
    storageBucket: 'barter-30a05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZDUuU-yGBHq9tIzzbfVgov2Mm8Jhyos',
    appId: '1:460987873980:ios:43b239512f7b1ff783aeb9',
    messagingSenderId: '460987873980',
    projectId: 'barter-30a05',
    storageBucket: 'barter-30a05.firebasestorage.app',
    androidClientId:
        '460987873980-227b1ntce91a9rds6l4tnk7r6fhkfr8t.apps.googleusercontent.com',
    iosClientId:
        '460987873980-mk49c4opdbb8duaht7beap5li4n7hgrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.barter',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDpLwQQpMlyMEyEZFi2YC-xKiQvA_TuX4E",
      authDomain: "barter-30a05.firebaseapp.com",
      projectId: "barter-30a05",
      storageBucket: "barter-30a05.firebasestorage.app",
      messagingSenderId: "460987873980",
      appId: "1:460987873980:web:fee9bfc0ed48109183aeb9",
      measurementId: "G-EDQKVSF7KQ");
}
